version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
    networks:
      bridge-network:
        aliases:
        - consulhost
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"
    hostname: "consulhost"
    
  consul-client:
    image: hashicorp/consul:1.10.0
    container_name: consul-client
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json:ro
    networks:
      bridge-network:
        aliases:
          - consulhost
    hostname: "consulhost"
    command: "agent"  
  
  london-weather-service:
    container_name: london-weather-service
    build:      
      context: .
      dockerfile: WeatherService/Dockerfile
    environment:      
      - ServiceName=London
      - ServiceHost=london-weather-service
      - ServicePort=60001
      - ConsulAddress=http://consulhost:8500    
    ports:
      - "60001:80"
    networks:
      bridge-network:
        aliases:
          - consulhost
          - 
  tokyo-weather-service:
    container_name: tokyo-weather-service
    build:
      context: .
      dockerfile: WeatherService/Dockerfile
    environment:
      - ServiceName=Tokyo
      - ServiceHost=tokyo-weather-service
      - ServicePort=60002
      - ConsulAddress=http://consulhost:8500
    ports:
      - "60002:80"
    networks:
      bridge-network:
        aliases:
          - consulhost    

networks:
  bridge-network:
    driver: bridge

